# NORMALIZATION PROBLEM

In [37]:
import numpy as np

#Create a random 5x5 ndarray
X = np.random.rand(5, 5)

#Calculate the mean and standard deviation of the array
mean_X = X.mean()
std_X = X.std()

#Normalize the array using the formula Z = (X - mean) / std
X_normalized = (X - mean_X) / std_X

#Save the normalized array to a file
np.save('X_normalized.npy', X_normalized)

#Print the original and normalized arrays
print("Original array:\n", X)
print("\nNormalized array:\n", X_normalized)


Original array:
 [[0.68221339 0.24348162 0.48906769 0.68280209 0.11327134]
 [0.15446677 0.59886454 0.43724193 0.48070557 0.45950388]
 [0.99099283 0.25129537 0.32829676 0.96337087 0.77079939]
 [0.23304704 0.56082799 0.92315525 0.93301181 0.10253061]
 [0.65951208 0.8886429  0.58069936 0.86500232 0.53988437]]

Normalized array:
 [[ 0.45634858 -1.14657528 -0.24931689  0.45849941 -1.62230368]
 [-1.47179456  0.15183024 -0.43866434 -0.27986822 -0.35732944]
 [ 1.58448644 -1.11802746 -0.83669982  1.48356854  0.78000101]
 [-1.18469845  0.01286221  1.33663918  1.37265051 -1.66154539]
 [ 0.37340842  1.21054694  0.08546304  1.12417514 -0.06365613]]


# DIVISIBLE BY 3 PROBLEM

In [19]:
import numpy as np

#Create an array with the first 100 positive integers
integers = np.arange(1, 101)

#Square each element to create the 10x10 array
A = integers ** 2
#Reshape to 10x10 ndarray
A = A.reshape(10, 10)

#Determine the elements divisible by 3
divisible_by_3 = A[A % 3 == 0]

#Save the result to a file
np.save('div_by_3.npy', divisible_by_3)

#Print the array and the elements divisible by 3
print("10x10 Array A:\n", A)
print("\nElements divisible by 3:\n", divisible_by_3)

10x10 Array A:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
